### ISSUE TITLE
SPracing F3 V1 flight controller

### ISSUE THREAD

**Issue by jasonkurohara** [alduxvm/pyMultiWii#22]
I am trying to read raw IMU data from a SPracing F3 V1 flight controller, but I can't seem to get any data on my Rasberry pi.  Looping the getData function returns "None".  Any advice?  I made sure I have the correct drivers. Thanks.

**Comment by alduxvm** [comment]
ok, did you tried ATT first? does that one works?

**Comment by jasonkurohara** [comment]
What is ATT?  Thank you!

**Comment by alduxvm** [comment]
Attitude

**Comment by jasonkurohara** [comment]
I was unable to get either readings .

**Comment by nicolas-coulon** [comment]
I have the same issue.
```python
from pymultiwii import MultiWii
import time

serialPort = "/dev/ttyACM0"
board = MultiWii(serialPort)
while True:
    board.getData(MultiWii.ATTITUDE)
    print(board.attitude)
    time.sleep(0.1)
```
Attitude works with Betaflight
Configurator: 10.4.0
Firmware: BTFL 3.2.0 (Target: OMNI)

**Comment by nicolas-coulon** [comment]
For me it's working now, I used python 3.6.5. It's working with python 2.7

**Comment by jasonkurohara** [comment]
Great! I'll give it a shot.
