### ISSUE TITLE
combinación de radio y rpi

### ISSUE THREAD

**Issue by Frankyshelley** [alduxvm/pyMultiWii#26]
Hola Aldo, Muchas gracias por este aporte, quisiera saber si es posible el control del drone tanto por la raspberry como por el radiocontrol ppm,  me gustaría controlarlo por radio y en momentos puntuales controlarlo por raspberry es posible??

Gracias!!

**Comment by alduxvm** [comment]
el gran problema al hacer eso es el firmware del naze32, la ultima vez que lo probe no soportaba tener dos canales de control... quizas se puede hacer, pero habria que preguntar en los foros de la firmware que estes usando, saludos!
