### ISSUE TITLE
MSP V2 protocol support

### ISSUE THREAD

**Issue by wx4cb** [alduxvm/pyMultiWii#28]
I know this is an "old" project, but is there any way that you can update to use the MSP V2 protocol?

it is described here: https://github.com/iNavFlight/inav/wiki/MSP-V2

Yes, i'm trying to talk to an INAV flight controller and it appears that it's because they use V2 of the MSP protocol.

**Comment by nik012003** [comment]
You can use OpenGS. It's on my GitHub and it's specifically made for iNav.

Right now I have only basic functionality(read attitude,read/write gps, r/w RC commands), but it's really easy to add new ones in.

**Comment by wx4cb** [comment]
i don't see an open GS repo in your profile or am i looking at the wrong place?

https://github.com/alduxvm

**Comment by nik012003** [comment]
I'm nik012003 not alduxvm.
Here's the link
https://github.com/nik012003/openGS

**Comment by wx4cb** [comment]
@nik012003 oops my bad. Thanks for the link. I'll take a proper look when i get home.

**Comment by nik012003** [comment]
@wx4cb No problem. If you want any help feel free to contact me on Skype (the username is nik012003).
