### ISSUE TITLE
Versioning + uploading to PyPI

### ISSUE THREAD

**Issue by amorphic** [alduxvm/pyMultiWii#5]
Thanks for an excellent Python module. We're experimenting with wifi drone flying at our makerspace [SparkCC](http://sparkcc.org/) and pyMultiWii saved us a lot of work!

It would be great if pyMultiWii was properly versioned and made available on [PyPI](https://pypi.python.org/pypi) so that it could be easily installed via [pip](https://pip.pypa.io/en/stable/) and included as a dependency in other projects.

Happy to help out with this if you'd like me to.

**Comment by alduxvm** [comment]
Hi! 

This sounds great!! (so sorry for not replying earlier...), yes I will be interested in doing that, how should we start doing it?

cheers!

**Comment by probhakarroy** [comment]
Just checkout this site!!!
http://peterdowns.com/posts/first-time-with-pypi.html

**Comment by probhakarroy** [comment]
Just checkout this site!!!
http://peterdowns.com/posts/first-time-with-pypi.html

And thanks for such a great module!!
