### ISSUE TITLE
Controlling the copter with a joystick

### ISSUE THREAD

**Issue by baitware** [alduxvm/pyMultiWii#7]
Hello! We are a bunch of students building a quadcopter as a school-project. We have no previous experience with copters or python but your solution is exactly what we've been looking for. 

We've managed to get it to arm through the arm-disarm test program but haven't gotten any further than that. It would be great if you could explain a bit more of how you controlled the copter with the joystick, since our ultimate goal is to control it with an xbox controller connected to the computer. 

Any help would be appreciated, thanks!

**Comment by alduxvm** [comment]
Hi! 

What FC do you have? what is the purpose of the project? Perhaps it is better to discuss this project in an email rather than an issue of this particular library... please send me an email to aldo@altax.net

Thanks a lot!
