### ISSUE TITLE
feature SERIALRX Invalid name

### ISSUE THREAD

**Issue by bigboateng** [alduxvm/pyMultiWii#8]
I want to use the library to send commands to my naze32,  but typing `feature SERIALRX` in the CLI gives invalid name error. Is this due to the version of cleanflight? If so do you know what the new command is, Many thanks.

**Comment by alduxvm** [comment]
Hi, yes, cleanflight is not supported, only baseflight is used and tested with this library. Probably in the future I will add support for cleanflight. Cheers!

**Comment by bigboateng** [comment]
Thanks for reply, is the firmware uploaded through baseflight different from the one uploaded through cleanflight? because I just tried same command and baseflight says invalid name for `feature SERIALRX`.

**Comment by alduxvm** [comment]
yes, the firmwares are different... Please reflash your board with baseflight and follow the instructions for activating the SERIALRX commands.

**Comment by bigboateng** [comment]
It worked now, thanks!
